In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
data=pd.read_csv(r'C:\Users\ATHUL AKSHAY\Desktop\Cancer\breast-cancer_csv.csv')
data.head()


age menopause tumor-size inv-nodes node-caps  deg-malig breast  \
0  40-49   premeno      15-19       0-2       yes          3  right   
1  50-59      ge40      15-19       0-2        no          1  right   
2  50-59      ge40      35-39       0-2        no          2   left   
3  40-49   premeno      35-39       0-2       yes          3  right   
4  40-49   premeno      30-34       3-5       yes          2   left   

  breast-quad irradiat                 Class  
0     left_up       no     recurrence-events  
1     central       no  no-recurrence-events  
2    left_low       no     recurrence-events  
3    left_low      yes  no-recurrence-events  
4    right_up       no     recurrence-events

In [2]:
data.shape

(286, 10)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   age          286 non-null    object
 1   menopause    286 non-null    object
 2   tumor-size   286 non-null    object
 3   inv-nodes    286 non-null    object
 4   node-caps    278 non-null    object
 5   deg-malig    286 non-null    int64 
 6   breast       286 non-null    object
 7   breast-quad  285 non-null    object
 8   irradiat     286 non-null    object
 9   Class        286 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.5+ KB


In [4]:
for column in data.columns:
    print(data[column].value_counts)
    print("*"*20)

<bound method IndexOpsMixin.value_counts of 0      40-49
1      50-59
2      50-59
3      40-49
4      40-49
       ...  
281    50-59
282    50-59
283    30-39
284    50-59
285    50-59
Name: age, Length: 286, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0      premeno
1         ge40
2         ge40
3      premeno
4      premeno
        ...   
281       ge40
282    premeno
283    premeno
284    premeno
285       ge40
Name: menopause, Length: 286, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0      15-19
1      15-19
2      35-39
3      35-39
4      30-34
       ...  
281    30-34
282    25-29
283    30-34
284    15-19
285    40-44
Name: tumor-size, Length: 286, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0      0-2
1      0-2
2      0-2
3      0-2
4      3-5
      ... 
281    6-8
282    3-5
283    6-8
284    0-2
285    0-2
Name: inv-nodes, Length: 286, dtype: object>
**************

In [5]:
data.isnull().sum()

age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      8
deg-malig      0
breast         0
breast-quad    1
irradiat       0
Class          0
dtype: int64

In [6]:
data["node-caps"]=data['node-caps'].fillna('yes')

In [7]:
data['breast-quad'].value_counts()

left_low     110
left_up       97
right_up      33
right_low     24
central       21
Name: breast-quad, dtype: int64

In [8]:
data['breast'].value_counts()

left     152
right    134
Name: breast, dtype: int64

In [9]:
data['node-caps'].value_counts()

no     222
yes     64
Name: node-caps, dtype: int64

In [10]:
data['deg-malig'].value_counts()

2    130
3     85
1     71
Name: deg-malig, dtype: int64

In [11]:
data['irradiat'].value_counts()

no     218
yes     68
Name: irradiat, dtype: int64

In [12]:
data['breast-quad']=data['breast-quad'].fillna('left_low')

In [13]:
data.isnull().sum()

age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      0
deg-malig      0
breast         0
breast-quad    0
irradiat       0
Class          0
dtype: int64

In [14]:
data['menopause'].value_counts()

premeno    150
ge40       129
lt40         7
Name: menopause, dtype: int64

In [15]:
data.dtypes

age            object
menopause      object
tumor-size     object
inv-nodes      object
node-caps      object
deg-malig       int64
breast         object
breast-quad    object
irradiat       object
Class          object
dtype: object

In [16]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
data['age']=label_encoder.fit_transform(data['age'])
data['menopause']=label_encoder.fit_transform(data['menopause'])
data['tumor-size']=label_encoder.fit_transform(data['tumor-size'])
data['inv-nodes']=label_encoder.fit_transform(data['inv-nodes'])
data['node-caps']=label_encoder.fit_transform(data['node-caps'])
data['breast']=label_encoder.fit_transform(data['breast'])
data['breast-quad']=label_encoder.fit_transform(data['breast-quad'])
data['irradiat']=label_encoder.fit_transform(data['irradiat'])
data['Class']=label_encoder.fit_transform(data['Class'])

In [17]:
data['age'].unique()

array([2, 3, 4, 1, 5, 0])

In [18]:
data['menopause'].unique()

array([2, 0, 1])

In [19]:
data['tumor-size'].unique()

array([ 2,  6,  5,  4,  7,  1,  0,  3,  8, 10,  9])

In [20]:
data['breast-quad'].unique()

array([2, 0, 1, 4, 3])

In [21]:
data['inv-nodes'].unique()

array([0, 4, 2, 5, 6, 3, 1])

In [22]:
data['node-caps'].unique()

array([1, 0])

In [23]:
data['breast'].unique()

array([1, 0])

In [24]:
data['irradiat'].unique()

array([0, 1])

In [25]:
data['Class'].unique()

array([1, 0])

In [26]:
data.dtypes

age            int32
menopause      int32
tumor-size     int32
inv-nodes      int32
node-caps      int32
deg-malig      int64
breast         int32
breast-quad    int32
irradiat       int32
Class          int32
dtype: object

In [27]:
data.Class.describe()

count    286.000000
mean       0.297203
std        0.457828
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000
Name: Class, dtype: float64

In [28]:
data.to_csv('bc cleaneddataset.csv')

In [29]:
data

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0      2          2           2          0          1          3       1   
1      3          0           2          0          0          1       1   
2      3          0           6          0          0          2       0   
3      2          2           6          0          1          3       1   
4      2          2           5          4          1          2       0   
..   ...        ...         ...        ...        ...        ...     ...   
281    3          0           5          5          1          2       0   
282    3          2           4          4          1          2       0   
283    1          2           5          5          1          2       1   
284    3          2           2          0          0          2       1   
285    3          0           7          0          0          3       0   

     breast-quad  irradiat  Class  
0              2         0      1  
1              0         0      0  
2              1         0      1  
3              1         1      0  
4              4         0      1  
..           ...       ...    ...  
281            1         0      0  
282            1         1      0  
283            4         0      0  
284            1         0      0  
285            4         0      0  

[286 rows x 10 columns]

In [30]:
x=data.drop(['Class'],axis=1)
y=data['Class']

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [33]:
x.shape

(286, 9)

In [34]:
print(x_train.shape)

(228, 9)


In [35]:
print(x_test.shape)

(58, 9)


In [36]:
# lo=LogisticRegression()
# lo.fit(x_train,y_train)
# y_pred_lo=lo.predict(x_test)
# r2_score(y_test,y_pred_lo)



In [37]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred_df=model.predict(x_test)
model

DecisionTreeClassifier()

In [38]:
# model.score(x_test,y_test)

In [39]:
# model.score(x_train,y_train)

In [40]:
ra=RandomForestClassifier()
ra.fit(x_train,y_train)
y_pred_rf=ra.predict(x_test)
y_pred_rf

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [41]:
ra.score(x_train,y_train)

0.9824561403508771

In [42]:

ra.score(x_test,y_test)

0.7241379310344828

In [43]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,explained_variance_score
from math import sqrt

In [44]:
evs=explained_variance_score(y_test,y_pred_rf)
evs

-0.045454545454545636

In [45]:
mae=mean_absolute_error(y_test,y_pred_rf)
mae

0.27586206896551724

In [46]:
mse=mean_squared_error(y_test,y_pred_rf)
mse

0.27586206896551724

In [47]:
sq=sqrt(mse)
sq

0.5252257314388902

In [48]:
from sklearn import metrics
metrics.r2_score(y_test,y_pred_rf)

-0.1717171717171717

In [49]:
import pickle 
ca=open('cancer.pkl','wb')
pickle.dump(ra,ca)

In [50]:
ca1=open('cancer.pkl','rb')
pkl=pickle.load(ca1)
pkl

RandomForestClassifier()

In [51]:
prediction=pkl.predict(x_test)
prediction

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])